rvm:
- 1.9.3
- 2.0.0
- 2.1.0
cache: bundler
sudo: false
notifications:
  irc:
    channels:
      - "irc.freenode.net#theodi"
    template:
      - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
